---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/ranchola/public_html/deploytest
    - export REPO_PATH=/home/renchola/repositories/slt-dev
    - export CONFIG_PATH=/home/renchola/configs-slt
    - echo "Copiando Hermosillo"
    - cp $REPO_PATH $DEPLOY_PATH/slt
    - cp $CONFIG_PATH/hmo_prod.php $DEPLOY_PATH/slt/config.php
    - echo "Copiando Hermosillo"
    - cp $REPO_PATH $DEPLOY_PATH/slt-nogales
    - cp $CONFIG_PATH/nog_prod.php $DEPLOY_PATH/slt-nogales/config.php
    - echo "Copiando Hermosillo"
    - cp $REPO_PATH $DEPLOY_PATH/slt-obregon
    - cp $CONFIG_PATH/obr_prod.php $DEPLOY_PATH/slt-obregon/config.php
    - echo "DEPLOY TERMINADO"
