---
deployment:
  tasks:
    - export BASE_PATH=/home/ranchola
    - export current_branch=$(git rev-parse --abbrev-ref HEAD)
    - |
      if [ "$current_branch" == "main" ]; then
        export DEPLOY_PATH=$BASE_PATH/public_html/deploy_prod
      elif [ "$current_branch" == "test" ]; then
        export DEPLOY_PATH=$BASE_PATH/public_html/deploy_test
      else
        echo "No deployment path defined for branch: $current_branch"
        exit 1
      fi
    - echo $DEPLOY_PATH
    - export REPO_PATH=$BASE_PATH/repositories/slt-dev
    - export CONFIG_PATH=$BASE_PATH/configs-slt

    - echo "Copiando Hermosillo"
    - rsync -a --exclude='.git' "$REPO_PATH" "$DEPLOY_PATH/slt/"
    - cp $CONFIG_PATH/hmo_prod.php $DEPLOY_PATH/slt/config.php
    
    - echo "Copiando Nogales"
    - rsync -a --exclude='.git' "$REPO_PATH" "$DEPLOY_PATH/slt-nogales/"
    - cp $CONFIG_PATH/nog_prod.php $DEPLOY_PATH/slt-nogales/config.php
    
    - echo "Copiando Obregon"
    - rsync -a --exclude='.git' "$REPO_PATH" "$DEPLOY_PATH/slt-obregon/"
    - cp $CONFIG_PATH/obr_prod.php $DEPLOY_PATH/slt-obregon/config.php
    - echo "DEPLOY TERMINADO"
